TRUNCATE TABLE STCBI106.RPRO_FACT_PRICE;
COMMIT;
INSERT INTO STCBI106.RPRO_FACT_PRICE
(
fldkey,
FLDFKEY,
FLDMAIN,
FLDSID,
FLDPRICELEVEL,
FLDPRICE,
FLDSTATUS,
DEPARTMENT_ID,
ITEM_ID,
RPRO_ITEM_ID,
PROG_CR_DT
)
SELECT
  A.FLDKEY PRC_fldkey
, A.FLDFKEY PRC_fldfkey
, A.FLDMAIN PRC_fldmain
, A.FLDSID PRC_fldsid
, A.FLDPRICELEVEL PRC_fldpricelevel
, A.FLDPRICE PRC_FLDprice
, A.FLDSTATUS PRC_fldstatus
,STC_DIM_DEPARTMENT.DEPARTMENT_ID,
STC_DIM_ITEM.ITEM_ID,
RPRO_DIM_ITEM.RPRO_ITEM_ID,
sysdate
FROM RPRO.TBLPRICES A
left outer join stcbi106.STC_DIM_COMPANIES STC_DIM_COMPANIES
ON (STC_DIM_COMPANIES.COMPANY_CODE IN 
(SELECT D.COMPANY_CODE FROM RPRO_MAPPING_ORION D 
WHERE A.FLDMAIN=D.MAIN_ID))
left outer join stcbi106.RPRO_DIM_ITEM RPRO_DIM_ITEM
ON (A.FLDFKEY = RPRO_DIM_ITEM.FLDKEY AND A.FLDMAIN=RPRO_DIM_ITEM.FLDMAIN),
RPRO.TBLITEMS B
left outer join stcbi106.STC_DIM_ITEM STC_DIM_ITEM
on (B.FLDDESC2 = STC_DIM_ITEM.ITEM_CODE)
left outer join stcbi106.STC_DIM_DEPARTMENT STC_DIM_DEPARTMENT
ON (ltrim(rtrim(STC_DIM_DEPARTMENT.DEPARTMENT_CODE)) = ltrim(rtrim(B.FLDDEPT)) AND
ltrim(rtrim(STC_DIM_DEPARTMENT.CLASS_CODE)) = ltrim(rtrim(B.FLDCLASS)) AND
ltrim(rtrim(STC_DIM_DEPARTMENT.SUB_CLASS_CODE)) = ltrim(rtrim(B.FLDSUBCLASS)))
WHERE A.FLDFKEY = B.FLDKEY ;
COMMIT;
EXIT;