TRUNCATE TABLE STCBI106.STC_FACT_LOCN_CURR_STK;
COMMIT;
Insert into  STCBI106.STC_FACT_LOCN_CURR_STK
(
  COMPANY_ID             ,
  LOCATION_ID            ,
  ITEM_ID                ,
  GRADE1_ID              ,
  GRADE2_ID              ,
  SIZE_ID                ,
  ARTICLE_ID             ,
  CAT_MANG_ID            ,
  CATEGORY_ID            ,
  PACKING_ID             ,
  FOOD_CAT_ID            ,
  LCS_COMP_CODE          ,
  LCS_LOCN_CODE          ,
  LCS_ITEM_CODE          ,
  LCS_GRADE_CODE_1       ,
  LCS_GRADE_CODE_2       ,
  LCS_STK_QTY_BU         ,
  LCS_RCVD_QTY_BU        ,
  LCS_ISSD_QTY_BU        ,
  LCS_RESV_QTY_BU        ,
  LCS_OVERRES_QTY_BU     ,
  LCS_HOLD_QTY_BU        ,
  LCS_REJECT_QTY_BU      ,
  LCS_PICK_QTY_BU        ,
  LCS_PACK_QTY_BU        ,
  LCS_RCVD_QTY_BU_1      ,
  LCS_RCVD_QTY_BU_2      ,
  LCS_RCVD_QTY_BU_3      ,
  LCS_RCVD_QTY_BU_4      ,
  LCS_RCVD_QTY_BU_5      ,
  LCS_ISSD_QTY_BU_1      ,
  LCS_ISSD_QTY_BU_2      ,
  LCS_ISSD_QTY_BU_3      ,
  LCS_ISSD_QTY_BU_4      ,
  LCS_ISSD_QTY_BU_5      ,
  PRO_AVAIL_SOLD_QTY_BU  ,
  LCS_CR_DT              ,
  LCS_CR_UID             ,
  LCS_UPD_DT             ,
  LCS_UPD_UID            ,
  PROG_ITEM_LENGTH       ,
  PROG_ITEM_WIDTH        ,
  PROG_ITEM_HEIGHT       ,
  IP_DIMENSION_UOM_CODE  ,
  IP_PACK_WEIGHT         ,
  IP_WEIGHT_UOM_CODE     ,
  PROG_ITEM_AREA         ,
  PROG_CBM               ,
  PROG_CBM_BU            ,
  IM_MANF_NAME           ,
  PROG_CR_DT             ,
  PROG_UPD_DT            ,
  prog_flex_vchar_01     ,
  ITEM_UOM_ID,
  DEPARTMENT_ID          
)
SELECT 
  STC_DIM_COMPANIES.COMP_ID             ,
  STC_DIM_LOCATION.LOCATION_ID            ,
  STC_DIM_ITEM.ITEM_ID                ,
  STC_DIM_GRADE1.GRADE1_ID              ,
  STC_DIM_GRADE2.GRADE2_ID              ,
  STC_DIM_SIZE.SIZE_ID                ,
  STC_DIM_ARTICLE.ARTICLE_ID             ,
  STC_DIM_CAT_MANG.CAT_MANG_ID            ,
  STC_DIM_CATEGORY.CATEGORY_ID            ,
  STC_DIM_PACKING.PACKING_ID             ,
  STC_DIM_FOOD_CAT.FOOD_CAT_ID            ,
  A.LCS_COMP_CODE          ,
  A.LCS_LOCN_CODE          ,
  A.LCS_ITEM_CODE          ,
  A.LCS_GRADE_CODE_1       ,
  A.LCS_GRADE_CODE_2       ,
  A.LCS_STK_QTY_BU         ,
  A.LCS_RCVD_QTY_BU        ,
  A.LCS_ISSD_QTY_BU        ,
  A.LCS_RESV_QTY_BU        ,
  A.LCS_OVERRES_QTY_BU     ,
  A.LCS_HOLD_QTY_BU        ,
  A.LCS_REJECT_QTY_BU      ,
  A.LCS_PICK_QTY_BU        ,
  A.LCS_PACK_QTY_BU        ,
  A.LCS_RCVD_QTY_BU_1      ,
  A.LCS_RCVD_QTY_BU_2      ,
  A.LCS_RCVD_QTY_BU_3      ,
  A.LCS_RCVD_QTY_BU_4      ,
  A.LCS_RCVD_QTY_BU_5      ,
  A.LCS_ISSD_QTY_BU_1      ,
  A.LCS_ISSD_QTY_BU_2      ,
  A.LCS_ISSD_QTY_BU_3      ,
  A.LCS_ISSD_QTY_BU_4      ,
  A.LCS_ISSD_QTY_BU_5      ,
  (A.LCS_STK_QTY_BU + A.LCS_RCVD_QTY_BU - (A.LCS_ISSD_QTY_BU  + A.LCS_RESV_QTY_BU  + A.LCS_OVERRES_QTY_BU + A.LCS_HOLD_QTY_BU + A.LCS_REJECT_QTY_BU + A.LCS_PICK_QTY_BU+ A.LCS_PACK_QTY_BU)) AS pro_avail_sold_qty_bu ,
  A.LCS_CR_DT              ,
  A.LCS_CR_UID             ,
  A.LCS_UPD_DT             ,
  A.LCS_UPD_UID            ,
  E.IP_PACK_LENGTH ,
  E.IP_PACK_WIDTH ,
  E.IP_PACK_HEIGHT,
  E.IP_DIMENSION_UOM_CODE ,
  E.IP_PACK_WEIGHT ,
  E.IP_WEIGHT_UOM_CODE ,
  (E.IP_PACK_LENGTH * E.IP_PACK_WIDTH)/10000 AS prog_ITEM_AREA ,
  (E.IP_PACK_LENGTH * E.IP_PACK_WIDTH * E.IP_PACK_HEIGHT)/1000000 AS prog_cbm ,
  (E.IP_PACK_LENGTH * E.IP_PACK_WIDTH * E.IP_PACK_HEIGHT * E.IP_MAX_QTY_BU)/1000000 AS prog_cbm_BU ,
  D.IM_MANF_NAME,
  SYSDATE,
  SYSDATE ,
  C.ITEM_UOM_CODE            ,
  STC_DIM_ITEM_UOM.ITEM_UOM_ID,
  STC_DIM_DEPARTMENT.DEPARTMENT_ID          
from
ORION106.OS_LOCN_CURR_STK@stcbi A
left outer join   STCBI106.STC_DIM_GRADE1 STC_DIM_GRADE1 on 
(A.LCS_GRADE_CODE_1 = STC_DIM_GRADE1.GRADE_CODE)
left outer join   STCBI106.STC_DIM_GRADE2 STC_DIM_GRADE2 on 
(A.LCS_GRADE_CODE_2 = STC_DIM_GRADE2.GRADE_CODE)
--left outer join   STCBI106.STC_DIM_LOCN_GROUP STC_DIM_LOCN_GROUP ON
--(A.CGCV_COST_GROUP_CODE = STC_DIM_LOCN_GROUP.LGD_CODE)
left outer join STCBI106.stc_dim_companies stc_dim_companies on 
(a.LCS_COMP_CODE = stc_dim_companies.company_code) 
left outer join   STCBI106.STC_DIM_location STC_DIM_location on 
(A.LCS_LOCN_code = STC_DIM_location.LOCN_CODE)
left outer join STCBI106.STC_DIM_ITEM STC_DIM_ITEM ON
(a.LCS_ITEM_CODE = STC_DIM_ITEM.ITEM_code)
,ORION106.OM_ITEM@stcbi C
LEFT OUTER JOIN STCBI106.STC_DIM_ITEM_UOM STC_DIM_ITEM_UOM ON
(C.ITEM_UOM_CODE = STC_DIM_ITEM_UOM.IU_UOM_CODE AND
C.ITEM_CODE = STC_DIM_ITEM_UOM.IU_ITEM_CODE)
left outer join   STCBI106.STC_DIM_CATEGORY STC_DIM_CATEGORY ON
(C.ITEM_ANLY_CODE_08 = STC_DIM_CATEGORY.CATEGORY_CODE)
left outer join   STCBI106.STC_DIM_DEPARTMENT STC_DIM_DEPARTMENT ON 
(C.ITEM_ANLY_CODE_02 = STC_DIM_DEPARTMENT.DEPARTMENT_CODE AND 
 C.ITEM_ANLY_CODE_06 = STC_DIM_DEPARTMENT.CLASS_CODE AND
 C.ITEM_ANLY_CODE_07 = STC_DIM_DEPARTMENT.SUB_CLASS_CODE)
left outer join   STCBI106.STC_DIM_ARTICLE STC_DIM_ARTICLE ON 
(C.ITEM_ANLY_CODE_10 = STC_DIM_ARTICLE.ARTICLE_CODE)
left outer join   STCBI106.STC_DIM_PACKING STC_DIM_PACKING ON
(C.ITEM_ANLY_CODE_11 = STC_DIM_PACKING.PACKING_CODE)
left outer join   STCBI106.STC_DIM_SIZE STC_DIM_SIZE ON
(C.ITEM_ANLY_CODE_12 = STC_DIM_SIZE.SIZE_CODE)
left outer join   STCBI106.STC_DIM_CAT_MANG STC_DIM_CAT_MANG ON
(C.ITEM_ANLY_CODE_13 = STC_DIM_CAT_MANG.CAT_MANG_CODE)
left outer join   STCBI106.STC_DIM_FOOD_CAT STC_DIM_FOOD_CAT ON
(C.ITEM_ANLY_CODE_03 = STC_DIM_FOOD_CAT.FOOD_CAT_CODE AND
C.ITEM_ANLY_CODE_04 = STC_DIM_FOOD_CAT.FOOD_SUB_CAT_CODE)
left outer join ORION106.OM_ITEM_MANF@STCBI D  
on (C.ITEM_CODE= D.IM_ITEM_CODE AND C.ITEM_UOM_CODE = D.IM_MANF_PART_NO)
left outer join ORION106.OM_ITEM_PACK@STCBI e 
on (C.ITEM_CODE= E.IP_ITEM_CODE and 
C.ITEM_UOM_CODE = E.IP_PACK_UOM_CODE)
where A.LCS_ITEM_CODE = C.ITEM_CODE AND-- ROWNUM<10 AND 
A.LCS_CR_DT >=  TO_DATE('1/jul/2009', 'DD/MM/YYYY') AND 
to_date(A.LCS_CR_DT,'DD/MM/YYYY')  < TO_DATE(SYSDATE, 'DD/MM/YYYY') ; 
commit;
delete from  STC_FACT_LOCN_CURR_STK WHERE LCS_COMP_CODE IN 
('261','277','278','280','286','287','205','210','213','255','269','283');
commit;
exit;